//quotes
static const char* quotes[] = {
  "Bismillaahir rohmaanir rohiim (1), Alhamdulillaahi robbil 'aalamiin (2), Arrohmaanir rohiim (3), Maaliki yawmid diin (4), Iyyaaka na'budu waiyyaaka nasta'iin (5), Ihdinash shiroothol mustaqiim (6), Shiroothol ladziina an'amta 'alaihim, Ghoiril maghdhuubi 'alaihim waladh dholliin (7]",
	"Dan dirikanlah shalat, tunaikanlah zakat dan ruku'lah beserta orang-orang yang ruku'. [al-Baqarah: 43]",
 	"Jadikanlah sabar dan shalat sebagai penolongmu. Dan sesungguhnya yang demikian itu sungguh berat, kecuali bagi orang-orang yang khusyu'. [al-Baqarah: 45]",
  "Dan ucapkanlah kata-kata yang baik kepada manusia. [al-Baqarah: 83]",
  "Dan berbuat baiklah, karena sesungguhnya Allah menyukai orang-orang yang berbuat baik. [al-Baqarah: 195]",
	"Peliharalah semua shalat(mu), dan (peliharalah) shalat wusthaa. Berdirilah untuk Allah (dalam shalatmu), dengan khusyu'. [al-Baqarah: 238]",
  "Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya. [al-Baqarah: 286]",
  //"Kemudian apabila kamu telah membulatkan tekad, maka bertawakkallah kepada Allah. Sesungguhnya Allah menyukai orang-orang yang bertawakkal kepada-Nya. ['Ali Imran: 159]",
  //"Cukuplah Allah menjadi Penolong kami dan Allah adalah sebaik-baik Pelindung. ['Ali Imran: 173]",
	//"Katakanlah sesungguhnya shalatku, ibadahku, hidupku, dan matiku hanyalah untuk Allah Rabb semesta alam. [al-An'am: 162]",
  //"Dialah yang menghidupkan dan mematikan, dan hanya kepada-Nya lah kamu akan dikembalikan. [Yunus: 56]",
  //"Sesungguhnya Tuhanku amat dekat lagi memperkenankan (doa hamba-Nya). [Huud: 61]",
  //"Dan mohonlah ampun kepada Tuhanmu kemudian bertaubatlah kepada-Nya. Sesungguhnya Tuhanku Maha Penyayang lagi Maha Pengasih. [Huud: 90]",
  //"Sesungguhnya perbuatan-perbuatan yang baik itu menghapuskan (dosa) perbuatan-perbuatan yang buruk. [Huud: 114]",
  //"Sesungguhnya Allah beserta orang-orang yang bertakwa dan orang-orang yang berbuat kebaikan. [an-Nahl: 128]",
  //"Dan jangan sekali-kali kamu mengatakan tentang sesuatu, Sesungguhnya aku akan mengerjakan ini besok pagi. kecuali (dengan menyebut): Insya Allah. [al-Kahfi: 23-24]",
  //"Janganlah kamu berdua khawatir, sesungguhnya Aku beserta kamu berdua, Aku mendengar dan melihat. [Thaha: 46]",
  //"Siapa yang taat kepada Allah dan Rasul-Nya, serta takut kepada Allah dan bertakwa kepada-Nya, mereka itulah orang-orang yang mendapat kemenangan. [an-Nur: 52]",
  //"dan apabila aku sakit, Dialah Yang menyembuhkan aku. [asy-Syu'ara: 80]",
  //"Dan carilah pada apa yang telah dianugerahkan kepadamu (kebahagiaan) negeri akhirat, dan janganlah kamu melupakan bagianmu dari (kenikmatan) duniawi. [al-Qashas: 77]",
  //"Sesungguhnya shalat itu mencegah dari perbuatan-perbuatan keji dan mungkar. [al-'Ankabut: 45]",
  //"Dan tiadalah kehidupan dunia ini melainkan hanya senda gurau dan main-main. Dan sesungguhnya akhirat itulah yang sebenarnya kehidupan, jika saja mereka mengetahui. [al-'Ankabut 64]",
  //"Dan bersabarlah kamu, sesungguhnya janji Allah adalah benar. [ar-Rum: 60]",
  //"Dan bertawakkallah kepada Allah. Dan cukuplah Allah sebagai Pemelihara. [al-Ahzab: 3]",
  //"Hai orang-orang yang beriman, Ingatlah kepada Allah sebanyak-banyaknya. [al-Ahzab: 41]",
  //"Maka jangan sekali-kali membiarkan kehidupan dunia ini memperdayakan kamu. [Fatir: 5]",
  //"Sesungguhnya hanya orang-orang yang bersabarlah yang dicukupkan pahala mereka tanpa batas. [az-Zumar: 10]",
  //"Kebaikan tidak sama dengan kejahatan. Tolaklah kejahatan itu dengan cara yang lebih baik, sehingga yang memusuhimu akan seperti teman yang setia. [Fusshilat: 34]",
  //"Tetapi orang yang bersabar dan memaafkan, sesungguhnya (perbuatan) yang demikian itu termasuk hal-hal yang diutamakan. [asy-Syuura: 43]",
  //"Maka nikmat Tuhan kamu yang manakah yang kamu dustakan?. [ar-Rahman]",
  //"Dan Allah sebaik-baik Pemberi rezeki. [al-Jumu'ah: 11]",
  //"Dan barang -siapa yang bertakwa kepada Allah, niscaya Allah menjadikan baginya kemudahan dalam urusannya. [ath-Thalaq: 4]",
  //"Karena sesungguhnya sesudah kesulitan itu ada kemudahan, sesungguhnya sesudah kesulitan itu ada kemudahan. [asy-Syarh: 5-6]",
  //"Dan adapun orang-orang yang takut pada kebesaran Tuhannya dan menahan diri dari keinginan hawa nafsunya, maka sesungguhnya surgalah tempat tinggal mereka. [an-Nazi'at: 40-41]",
  //"Tidakkah dia menyadari bahwa sesungguhnya Allah melihat segala perbuatannya?. [al-'Alaq: 14]",
  //"Barangsiapa yang mengerjakan kebaikan sekecil apapun, niscaya dia akan melihat (balasan)Nya. [al-Zalzalah: 7]",
  //"Kecelakaanlah bagi setiap pengumpat dan pencela, yang mengumpulkan harta dan menghitung-hitungnya. Dia mengira bahwa hartanya dapat menyelamatkannya. [al-Humazah: 1-3]",
  //"Jika engkau berkata pada sahabatmu pada hari Jum'at, ‘Diamlah, khotib sedang berkhutbah!' Sungguh engkau telah berkata sia-sia. [HR. Bukhari no. 934 dan Muslim no. 851]",
  //"Makan sahurlah kalian karena dalam makan sahur terdapat keberkahan. [HR. Bukhari no. 1923 dan Muslim no. 1095]",
  //"Apabila Ramadhan tiba, pintu surga dibuka, pintu neraka ditutup, dan setan pun dibelenggu. [HR. Bukhari no. 3277 dan Muslim no. 1079]",
  //"Sesungguhnya umrah di bulan Ramadhan seperti berhaji bersamaku. [HR. Bukhari no. 1863]",
  //"Barangsiapa melaksanakan salat pada malam lailatul qodar karena iman dan mengharap pahala dari Allah, maka dosa-dosanya yang telah lalu akan diampuni. [HR. Bukhari no. 1901]",
  //"Shalat jamaah lebih baik 27 derajat dibanding shalat sendirian. [HR. Bukhari no. 645 dan Muslim no. 650]",
  //"Seorang hamba berada paling dekat dengan Rabb-nya ialah ketika ia sedang bersujud. Maka perbanyaklah berdoa ketika itu. [HR. Muslim no.482]",
  //"Amalan yang paling dicintai oleh Allah adalah amalan yang kontinyu (ajeg), walaupun sedikit. [HR. Muslim no. 782]",
  //"Kalau aku masih hidup tahun depan, maka sungguh aku akan berpuasa pada tanggal 9 Muharram (bersama 10 Muharram). [HR.Muslim: no. 1134]",
  //"Orang yang berpuasa memiliki 2 kebahagiaan: kebahagiaan ketika berbuka puasa dan kebahagiaan ketika bertemu dengan Rabb-Nya kelak. [HR. Muslim no.1151]",
  //"Puasa 'Asyura akan menghapus dosa setahun yang lalu. [HR. Muslim no. 1162]",
  //"Umrah pada bulan Ramadhan senilai dengan haji. [HR. Muslim no. 1256]",
  //"Sesungguhnya Allah meninggikan derajat seseorang melalui al-Qur'an ini dan merendahkan sebagian lainnya. [HR. Muslim no.1353]",
  //"Dunia adalah penjara bagi orang beriman dan surga bagi orang kafir. [HR. Muslim no. 2392]",
  //"Doa di antara adzan dan iqamah tidak tertolak. [HR. Tirmidzi 212]",
  //"Sedekah itu dapat memadamkan murka Allah dan mencegah dari keadaan mati yang jelek. [HR. Tirmidzi no. 664]",
  //"Ada yang bertanya: Wahai Rasulullah, kapan doa kita didengar oleh Allah? Beliau bersabda: Di akhir malam dan di akhir shalat wajib. [HR. Tirmidzi no. 3499]",
  //"Doa yang terbaik adalah doa ketika hari Arafah. [HR. Tirmidzi no. 3585]",
  //"Tiga orang yang do'anya tidak tertolak: orang yang berpuasa sampai ia berbuka, pemimpin yang adil, dan do'a orang yang dizholimi. [HR. Tirmidzi no. 3598]",
  //"Puasa adalah perisai yang dapat melindungi seorang hamba dari siksa neraka. [HR. Ahmad, Juz 3 no. 396]",
  //"Jagalah dzikir pagi dan sore untuk perlindungan diri",
  //"Perbanyak doa kepada Allah untuk keselamatan diri dan keluarga",
  //"Matikan HP ketika masuk Masjid",
  //"Jangan Merokok di dalam Masjid",*/
};